#!/usr/bin/env bash
  
path_to_getenforce=$(which getenforce 2> /dev/null)
if [ ! -x "$path_to_getenforce" ] ; then
  echo 'UNKNOWN: getenforce not found in $PATH'
  exit 3
fi
SESTATUS=`$path_to_getenforce`

case $SESTATUS in
  Enforcing)
    echo "OK: SELinux Enforcing"
    exit 0
    ;;

  Permissive)
    echo "WARNING: SELinux Permissive"
    exit 1
    ;;

  Disabled)
    echo "CRITICAL: SELinux Disabled"
    exit 2
    ;;

  *)
    echo "UNKNOWN: Failed to get SELinux state"
    exit 3
    ;;
esac
