#!/usr/bin/python

import requests
import json
import sys

notify = ['Mountain of Meat','Tabasco Pepperoni']

url = 'https://www.thepie.com/index.php?option=com_dpcalendar&view=events&format=raw&limit=0&date-start=today&date-end=today'
headers = {
    'Content-type':    'application/json',
    'User-Agent':      'Slice of the day checker',
    'Accept-Language': 'en-US,en;q=0.5',
}


response = requests.post(url, headers=headers)
j_response = json.loads(response.text)

sotd = j_response['data'][0]['title']

print(sotd + ' today at The Pie')
if(sotd in notify):
    sys.exit(1)
else:
    sys.exit(0)
